### ISSUE TITLE
Controls exception

### ISSUE THREAD

**Issue by echiteri** [ilabafrica/iBLIS#377]
The following is a stacktrace of the exception thrown when control is selected after upgrading from version 2.5 to 2.6.

[2016-06-10 11:56:24] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/ezekiel/git/iBLIS_redundunt/app/storage/views/932686457c085901f620444c8ec89ad1:36
Stack trace:
#0 /home/ezekiel/git/iBLIS_redundunt/app/storage/views/932686457c085901f620444c8ec89ad1(36): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/ezekiel/g...', 36, Array)
#1 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/home/ezekiel/g...')
#2 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/ezekiel/g...', Array)
#3 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/View.php(140): Illuminate\View\Engines\CompilerEngine->get('/home/ezekiel/g...', Array)
#4 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/View.php(109): Illuminate\View\View->getContents()
#5 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/View.php(78): Illuminate\View\View->renderContents()
#6 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#7 /home/ezekiel/git/iBLIS_redundunt/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#9 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#10 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/ezekiel/git/iBLIS_redundunt/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /home/ezekiel/git/iBLIS_redundunt/public/index.php(49): Illuminate\Foundation\Application->run()
#19 /home/ezekiel/git/iBLIS_redundunt/server.php(19): require_once('/home/ezekiel/g...')
#20 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /home/ezekiel/git/iBLIS_redundunt/app/views/control/index.blade.php)' in /home/ezekiel/git/iBLIS_redundunt/app/storage/views/932686457c085901f620444c8ec89ad1:36
Stack trace:
#0 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/ezekiel/g...', Array)
#2 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/View.php(140): Illuminate\View\Engines\CompilerEngine->get('/home/ezekiel/g...', Array)
#3 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/View.php(109): Illuminate\View\View->getContents()
#4 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/View/View.php(78): Illuminate\View\View->renderContents()
#5 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /home/ezekiel/git/iBLIS_redundunt/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/ezekiel/git/iBLIS_redundunt/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/ezekiel/git/iBLIS_redundunt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /home/ezekiel/git/iBLIS_redundunt/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /home/ezekiel/git/iBLIS_redundunt/server.php(19): require_once('/home/ezekiel/g...')

**Comment by Piusyo** [comment]
@echiteri 
Can you provide the db dump you are using since from my side the control seems to work fine. 
Since in the case error is " ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' " its likely that something is missing in the db.
It will greatly help understand the problem.
You can try it using the test data.

**Comment by echiteri** [comment]
@Piusyo I am not able to provide the db dump at this time. But you can repeat the error if you follow these steps:
1. Install the instance of the old version 2.5
2. Upgrade to the new version 2.6 and run migrate and seed.
3. Login and select controls menu
4. An exception will be thrown.

Pointers, the old version db, the controls table has a column named lot_id, in the new db migration it is named instrument_id. The bug is springing from there.

Regards

**Comment by briankip** [comment]
Hi @echiteri are you facing these issues still?
